/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AccessTokenResponseTokenTypeEnum {
    BEARER("Bearer");

    @JsonValue
    public final String value;

    private AccessTokenResponseTokenTypeEnum(String value) {
        this.value = value;
    }
}
