/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AccessTokenRequestGrantTypeEnum {
    CLIENT_CREDENTIALS("client_credentials"),
    AUTHORIZATION_CODE("authorization_code");

    @JsonValue
    public final String value;

    private AccessTokenRequestGrantTypeEnum(String value) {
        this.value = value;
    }
}
