/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ApplicationSecretResponse - Create an application secret
 */
public class ApplicationSecretResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client_secret")
    public String clientSecret;
    public ApplicationSecretResponse withClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expires_in")
    public Long expiresIn;
    public ApplicationSecretResponse withExpiresIn(Long expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }
    
    @JsonProperty("id")
    public String id;
    public ApplicationSecretResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("name")
    public String name;
    public ApplicationSecretResponse withName(String name) {
        this.name = name;
        return this;
    }
    
    public ApplicationSecretResponse(@JsonProperty("id") String id, @JsonProperty("name") String name) {
        this.id = id;
        this.name = name;
  }
}
