/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ApplicationsResponse - Get Applications
 */
public class ApplicationsResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("applications")
    public ApplicationResponse[] applications;
    public ApplicationsResponse withApplications(ApplicationResponse[] applications) {
        this.applications = applications;
        return this;
    }
    
    public ApplicationsResponse(){}
}
