/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ClientsResponse - Gets a list of clients.
 */
public class ClientsResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("clients")
    public ClientResponse[] clients;
    public ClientsResponse withClients(ClientResponse[] clients) {
        this.clients = clients;
        return this;
    }
    
    public ClientsResponse(){}
}
