/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Jwks - JWKS
 */
public class Jwks {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("keys")
    public Jwk[] keys;
    public Jwks withKeys(Jwk[] keys) {
        this.keys = keys;
        return this;
    }
    
    public Jwks(){}
}
