/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;

public class PasswordAuthRequest {
    @SpeakeasyMetadata("multipartForm:name=password")
    public String password;
    public PasswordAuthRequest withPassword(String password) {
        this.password = password;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=username")
    public String username;
    public PasswordAuthRequest withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public PasswordAuthRequest(){}
}
