/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ScopesResponse - Gets a list of clients.
 */
public class ScopesResponse {
    @JsonProperty("scopes")
    public ScopeResponse[] scopes;
    public ScopesResponse withScopes(ScopeResponse[] scopes) {
        this.scopes = scopes;
        return this;
    }
    
    public ScopesResponse(@JsonProperty("scopes") ScopeResponse[] scopes) {
        this.scopes = scopes;
  }
}
