/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TemplateRequest {
    @JsonProperty("authorizationServerId")
    public String authorizationServerId;
    public TemplateRequest withAuthorizationServerId(String authorizationServerId) {
        this.authorizationServerId = authorizationServerId;
        return this;
    }
    
    @JsonProperty("template")
    public String template;
    public TemplateRequest withTemplate(String template) {
        this.template = template;
        return this;
    }
    
    @JsonProperty("templateType")
    public TemplateTypeEnumEnum templateType;
    public TemplateRequest withTemplateType(TemplateTypeEnumEnum templateType) {
        this.templateType = templateType;
        return this;
    }
    
    public TemplateRequest(@JsonProperty("authorizationServerId") String authorizationServerId, @JsonProperty("template") String template, @JsonProperty("templateType") TemplateTypeEnumEnum templateType) {
        this.authorizationServerId = authorizationServerId;
        this.template = template;
        this.templateType = templateType;
  }
}
