/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WellKnownResponseTypesSupportedEnum {
    CODE("code"),
    TOKEN("token"),
    CODE_ID_TOKEN("code id_token");

    @JsonValue
    public final String value;

    private WellKnownResponseTypesSupportedEnum(String value) {
        this.value = value;
    }
}
