/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WellKnownCodeChallengeMethodsSupportedEnum {
    S256("S256");

    @JsonValue
    public final String value;

    private WellKnownCodeChallengeMethodsSupportedEnum(String value) {
        this.value = value;
    }
}
