/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WellKnownTokenEndpointAuthMethodsSupportedEnum {
    CLIENT_SECRET_POST("client_secret_post"),
    CLIENT_SECRET_BASIC("client_secret_basic");

    @JsonValue
    public final String value;

    private WellKnownTokenEndpointAuthMethodsSupportedEnum(String value) {
        this.value = value;
    }
}
