/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WellKnownIdTokenSigningAlgValuesSupportedEnum {
    RS256("RS256"),
    RS512("RS512"),
    ED_DSA("EdDSA");

    @JsonValue
    public final String value;

    private WellKnownIdTokenSigningAlgValuesSupportedEnum(String value) {
        this.value = value;
    }
}
