"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import applicationsecretresponse as shared_applicationsecretresponse
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ApplicationSecretsResponse:
    r"""List the secrets"""
    
    application_secrets: list[shared_applicationsecretresponse.ApplicationSecretResponse] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('applicationSecrets') }})
    