"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AuthorizationServerRequest:
    
    audience: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('audience') }})
    authorization_code_token_expiration: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authorizationCodeTokenExpiration') }})
    client_credentials_token_expiration: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('clientCredentialsTokenExpiration') }})
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    server_url: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('serverUrl') }})
    