"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import authorizationserverresponse as shared_authorizationserverresponse
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AuthorizationServersResponse:
    r"""Get a list of the authorization servers."""
    
    authorization_servers: Optional[list[shared_authorizationserverresponse.AuthorizationServerResponse]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authorizationServers'), 'exclude': lambda f: f is None }})
    