/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DeleteApplicationSecretRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=applicationId")
    public String applicationId;
    public DeleteApplicationSecretRequest withApplicationId(String applicationId) {
        this.applicationId = applicationId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=secretId")
    public String secretId;
    public DeleteApplicationSecretRequest withSecretId(String secretId) {
        this.secretId = secretId;
        return this;
    }
    
    public DeleteApplicationSecretRequest(@JsonProperty("applicationId") String applicationId, @JsonProperty("secretId") String secretId) {
        this.applicationId = applicationId;
        this.secretId = secretId;
  }
}
