/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class IssueTokenRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.cartobucket.auth.api.models.shared.AccessTokenRequest accessTokenRequest;
    public IssueTokenRequest withAccessTokenRequest(com.cartobucket.auth.api.models.shared.AccessTokenRequest accessTokenRequest) {
        this.accessTokenRequest = accessTokenRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=authorizationServerId")
    public String authorizationServerId;
    public IssueTokenRequest withAuthorizationServerId(String authorizationServerId) {
        this.authorizationServerId = authorizationServerId;
        return this;
    }
    
    public IssueTokenRequest(@JsonProperty("AccessTokenRequest") com.cartobucket.auth.api.models.shared.AccessTokenRequest accessTokenRequest, @JsonProperty("authorizationServerId") String authorizationServerId) {
        this.accessTokenRequest = accessTokenRequest;
        this.authorizationServerId = authorizationServerId;
  }
}
