/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateTemplateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.cartobucket.auth.api.models.shared.TemplateRequest templateRequest;
    public UpdateTemplateRequest withTemplateRequest(com.cartobucket.auth.api.models.shared.TemplateRequest templateRequest) {
        this.templateRequest = templateRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=templateId")
    public String templateId;
    public UpdateTemplateRequest withTemplateId(String templateId) {
        this.templateId = templateId;
        return this;
    }
    
    public UpdateTemplateRequest(@JsonProperty("TemplateRequest") com.cartobucket.auth.api.models.shared.TemplateRequest templateRequest, @JsonProperty("templateId") String templateId) {
        this.templateRequest = templateRequest;
        this.templateId = templateId;
  }
}
