/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateApplicationSecretResponse {
    /**
     * Create an application secret
     */
    
    public com.cartobucket.auth.api.models.shared.ApplicationSecretResponse applicationSecretResponse;
    public CreateApplicationSecretResponse withApplicationSecretResponse(com.cartobucket.auth.api.models.shared.ApplicationSecretResponse applicationSecretResponse) {
        this.applicationSecretResponse = applicationSecretResponse;
        return this;
    }
    
    
    public String contentType;
    public CreateApplicationSecretResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public CreateApplicationSecretResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public CreateApplicationSecretResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public CreateApplicationSecretResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
