/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateAuthorizationCodeRequest {
    @SpeakeasyMetadata("request:mediaType=multipart/form-data")
    public com.cartobucket.auth.api.models.shared.PasswordAuthRequest passwordAuthRequest;
    public CreateAuthorizationCodeRequest withPasswordAuthRequest(com.cartobucket.auth.api.models.shared.PasswordAuthRequest passwordAuthRequest) {
        this.passwordAuthRequest = passwordAuthRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=authorizationServerId")
    public String authorizationServerId;
    public CreateAuthorizationCodeRequest withAuthorizationServerId(String authorizationServerId) {
        this.authorizationServerId = authorizationServerId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;
    public CreateAuthorizationCodeRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=code_challenge")
    public String codeChallenge;
    public CreateAuthorizationCodeRequest withCodeChallenge(String codeChallenge) {
        this.codeChallenge = codeChallenge;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=code_challenge_method")
    public String codeChallengeMethod;
    public CreateAuthorizationCodeRequest withCodeChallengeMethod(String codeChallengeMethod) {
        this.codeChallengeMethod = codeChallengeMethod;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=nonce")
    public String nonce;
    public CreateAuthorizationCodeRequest withNonce(String nonce) {
        this.nonce = nonce;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=redirect_uri")
    public String redirectUri;
    public CreateAuthorizationCodeRequest withRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=response_type")
    public CreateAuthorizationCodeResponseTypeEnum responseType;
    public CreateAuthorizationCodeRequest withResponseType(CreateAuthorizationCodeResponseTypeEnum responseType) {
        this.responseType = responseType;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scope")
    public String scope;
    public CreateAuthorizationCodeRequest withScope(String scope) {
        this.scope = scope;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=state")
    public String state;
    public CreateAuthorizationCodeRequest withState(String state) {
        this.state = state;
        return this;
    }
    
    public CreateAuthorizationCodeRequest(@JsonProperty("PasswordAuthRequest") com.cartobucket.auth.api.models.shared.PasswordAuthRequest passwordAuthRequest, @JsonProperty("authorizationServerId") String authorizationServerId, @JsonProperty("client_id") String clientId, @JsonProperty("response_type") CreateAuthorizationCodeResponseTypeEnum responseType) {
        this.passwordAuthRequest = passwordAuthRequest;
        this.authorizationServerId = authorizationServerId;
        this.clientId = clientId;
        this.responseType = responseType;
  }
}
