/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DeleteUserRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=userId")
    public String userId;
    public DeleteUserRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public DeleteUserRequest(@JsonProperty("userId") String userId) {
        this.userId = userId;
  }
}
