/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DeleteTemplateRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=templateId")
    public String templateId;
    public DeleteTemplateRequest withTemplateId(String templateId) {
        this.templateId = templateId;
        return this;
    }
    
    public DeleteTemplateRequest(@JsonProperty("templateId") String templateId) {
        this.templateId = templateId;
  }
}
