/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetAuthorizationServerJwksResponse {
    
    public String contentType;
    public GetAuthorizationServerJwksResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * JWKS
     */
    
    public com.cartobucket.auth.api.models.shared.Jwks jwks;
    public GetAuthorizationServerJwksResponse withJwks(com.cartobucket.auth.api.models.shared.Jwks jwks) {
        this.jwks = jwks;
        return this;
    }
    
    
    public Integer statusCode;
    public GetAuthorizationServerJwksResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetAuthorizationServerJwksResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetAuthorizationServerJwksResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
