/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOpenIdConnectionWellKnownResponse {
    
    public String contentType;
    public GetOpenIdConnectionWellKnownResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetOpenIdConnectionWellKnownResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetOpenIdConnectionWellKnownResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Returns a well-known configuration object.
     */
    
    public com.cartobucket.auth.api.models.shared.WellKnown wellKnown;
    public GetOpenIdConnectionWellKnownResponse withWellKnown(com.cartobucket.auth.api.models.shared.WellKnown wellKnown) {
        this.wellKnown = wellKnown;
        return this;
    }
    
    public GetOpenIdConnectionWellKnownResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
