/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetUserInfoRequest {
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Authorization")
    public String authorization;
    public GetUserInfoRequest withAuthorization(String authorization) {
        this.authorization = authorization;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=authorizationServerId")
    public String authorizationServerId;
    public GetUserInfoRequest withAuthorizationServerId(String authorizationServerId) {
        this.authorizationServerId = authorizationServerId;
        return this;
    }
    
    public GetUserInfoRequest(@JsonProperty("Authorization") String authorization, @JsonProperty("authorizationServerId") String authorizationServerId) {
        this.authorization = authorization;
        this.authorizationServerId = authorizationServerId;
  }
}
