/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class InitiateAuthorizationResponse {
    
    public String contentType;
    public InitiateAuthorizationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public InitiateAuthorizationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public InitiateAuthorizationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Login screen
     */
    
    public String initiateAuthorization200TextHTMLString;
    public InitiateAuthorizationResponse withInitiateAuthorization200TextHTMLString(String initiateAuthorization200TextHTMLString) {
        this.initiateAuthorization200TextHTMLString = initiateAuthorization200TextHTMLString;
        return this;
    }
    
    public InitiateAuthorizationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
