/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class InitiateAuthorizationRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=authorizationServerId")
    public String authorizationServerId;
    public InitiateAuthorizationRequest withAuthorizationServerId(String authorizationServerId) {
        this.authorizationServerId = authorizationServerId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=client_id")
    public String clientId;
    public InitiateAuthorizationRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=code_challenge")
    public String codeChallenge;
    public InitiateAuthorizationRequest withCodeChallenge(String codeChallenge) {
        this.codeChallenge = codeChallenge;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=code_challenge_method")
    public String codeChallengeMethod;
    public InitiateAuthorizationRequest withCodeChallengeMethod(String codeChallengeMethod) {
        this.codeChallengeMethod = codeChallengeMethod;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=nonce")
    public String nonce;
    public InitiateAuthorizationRequest withNonce(String nonce) {
        this.nonce = nonce;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=redirect_uri")
    public String redirectUri;
    public InitiateAuthorizationRequest withRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=response_type")
    public InitiateAuthorizationResponseTypeEnum responseType;
    public InitiateAuthorizationRequest withResponseType(InitiateAuthorizationResponseTypeEnum responseType) {
        this.responseType = responseType;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scope")
    public String scope;
    public InitiateAuthorizationRequest withScope(String scope) {
        this.scope = scope;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=state")
    public String state;
    public InitiateAuthorizationRequest withState(String state) {
        this.state = state;
        return this;
    }
    
    public InitiateAuthorizationRequest(@JsonProperty("authorizationServerId") String authorizationServerId, @JsonProperty("client_id") String clientId, @JsonProperty("response_type") InitiateAuthorizationResponseTypeEnum responseType) {
        this.authorizationServerId = authorizationServerId;
        this.clientId = clientId;
        this.responseType = responseType;
  }
}
