/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListAuthorizationServersResponse {
    /**
     * Get a list of the authorization servers.
     */
    
    public com.cartobucket.auth.api.models.shared.AuthorizationServersResponse authorizationServersResponse;
    public ListAuthorizationServersResponse withAuthorizationServersResponse(com.cartobucket.auth.api.models.shared.AuthorizationServersResponse authorizationServersResponse) {
        this.authorizationServersResponse = authorizationServersResponse;
        return this;
    }
    
    
    public String contentType;
    public ListAuthorizationServersResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ListAuthorizationServersResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListAuthorizationServersResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListAuthorizationServersResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
