/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListScopesResponse {
    
    public String contentType;
    public ListScopesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Gets a list of clients.
     */
    
    public com.cartobucket.auth.api.models.shared.ScopesResponse scopesResponse;
    public ListScopesResponse withScopesResponse(com.cartobucket.auth.api.models.shared.ScopesResponse scopesResponse) {
        this.scopesResponse = scopesResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public ListScopesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListScopesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListScopesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
