/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UpdateAuthorizationServerResponse {
    /**
     * Update the full body of an Authorization Server.
     */
    
    public com.cartobucket.auth.api.models.shared.AuthorizationServerResponse authorizationServerResponse;
    public UpdateAuthorizationServerResponse withAuthorizationServerResponse(com.cartobucket.auth.api.models.shared.AuthorizationServerResponse authorizationServerResponse) {
        this.authorizationServerResponse = authorizationServerResponse;
        return this;
    }
    
    
    public String contentType;
    public UpdateAuthorizationServerResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public UpdateAuthorizationServerResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public UpdateAuthorizationServerResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public UpdateAuthorizationServerResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
