"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import templateresponse as shared_templateresponse
from typing import Optional


@dataclasses.dataclass
class CreateTemplateResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    template_response: Optional[shared_templateresponse.TemplateResponse] = dataclasses.field(default=None)
    r"""Creates a new client."""
    