"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientresponse as shared_clientresponse
from typing import Optional


@dataclasses.dataclass
class CreateClientResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    client_response: Optional[shared_clientresponse.ClientResponse] = dataclasses.field(default=None)
    r"""Creates a new client."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    