"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from enum import Enum
from typing import Optional

class InitiateAuthorizationResponseTypeEnum(str, Enum):
    CODE = 'code'
    CLIENT_CREDENTIALS = 'client_credentials'


@dataclasses.dataclass
class InitiateAuthorizationRequest:
    
    authorization_server_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'authorizationServerId', 'style': 'simple', 'explode': False }})
    client_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'client_id', 'style': 'form', 'explode': True }})
    response_type: InitiateAuthorizationResponseTypeEnum = dataclasses.field(metadata={'query_param': { 'field_name': 'response_type', 'style': 'form', 'explode': True }})
    code_challenge: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'code_challenge', 'style': 'form', 'explode': True }})
    code_challenge_method: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'code_challenge_method', 'style': 'form', 'explode': True }})
    nonce: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'nonce', 'style': 'form', 'explode': True }})
    redirect_uri: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'redirect_uri', 'style': 'form', 'explode': True }})
    scope: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'scope', 'style': 'form', 'explode': True }})
    state: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'state', 'style': 'form', 'explode': True }})
    

@dataclasses.dataclass
class InitiateAuthorizationResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    initiate_authorization_200_text_html_string: Optional[str] = dataclasses.field(default=None)
    r"""Login screen"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    