"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import authorizationserversresponse as shared_authorizationserversresponse
from typing import Optional


@dataclasses.dataclass
class ListAuthorizationServersResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    authorization_servers_response: Optional[shared_authorizationserversresponse.AuthorizationServersResponse] = dataclasses.field(default=None)
    r"""Get a list of the authorization servers."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    