"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientrequest as shared_clientrequest
from ..shared import clientresponse as shared_clientresponse
from typing import Optional


@dataclasses.dataclass
class UpdateClientRequest:
    
    client_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'clientId', 'style': 'simple', 'explode': False }})
    r"""The clientId of the resource."""
    client_request: shared_clientrequest.ClientRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    

@dataclasses.dataclass
class UpdateClientResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    client_response: Optional[shared_clientresponse.ClientResponse] = dataclasses.field(default=None)
    r"""Update the whole client."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    