"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import jwks as shared_jwks
from typing import Optional


@dataclasses.dataclass
class GetAuthorizationServerJwksRequest:
    
    authorization_server_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'authorizationServerId', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class GetAuthorizationServerJwksResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    jwks: Optional[shared_jwks.Jwks] = dataclasses.field(default=None)
    r"""JWKS"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    