"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import wellknown as shared_wellknown
from typing import Optional


@dataclasses.dataclass
class GetOpenIDConnectionWellKnownRequest:
    
    authorization_server_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'authorizationServerId', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class GetOpenIDConnectionWellKnownResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    well_known: Optional[shared_wellknown.WellKnown] = dataclasses.field(default=None)
    r"""Returns a well-known configuration object."""
    