"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import usersresponse as shared_usersresponse
from typing import Optional


@dataclasses.dataclass
class ListUsersRequest:
    
    authorization_server_ids: Optional[list[str]] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'authorizationServerIds', 'style': 'form', 'explode': True }})
    

@dataclasses.dataclass
class ListUsersResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    users_response: Optional[shared_usersresponse.UsersResponse] = dataclasses.field(default=None)
    r"""Get a list of User."""
    