"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import scopesresponse as shared_scopesresponse
from typing import Optional


@dataclasses.dataclass
class ListScopesRequest:
    
    authorization_server_ids: Optional[list[str]] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'authorizationServerIds', 'style': 'form', 'explode': True }})
    

@dataclasses.dataclass
class ListScopesResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    scopes_response: Optional[shared_scopesresponse.ScopesResponse] = dataclasses.field(default=None)
    r"""Gets a list of clients."""
    