"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import applicationsecretsresponse as shared_applicationsecretsresponse
from typing import Optional


@dataclasses.dataclass
class ListApplicationSecretsRequest:
    
    application_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'applicationId', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class ListApplicationSecretsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    application_secrets_response: Optional[shared_applicationsecretsresponse.ApplicationSecretsResponse] = dataclasses.field(default=None)
    r"""List the secrets"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    