"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import authorizationserverrequest as shared_authorizationserverrequest
from ..shared import authorizationserverresponse as shared_authorizationserverresponse
from typing import Optional


@dataclasses.dataclass
class UpdateAuthorizationServerRequest:
    
    authorization_server_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'authorizationServerId', 'style': 'simple', 'explode': False }})
    authorization_server_request: shared_authorizationserverrequest.AuthorizationServerRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    

@dataclasses.dataclass
class UpdateAuthorizationServerResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    authorization_server_response: Optional[shared_authorizationserverresponse.AuthorizationServerResponse] = dataclasses.field(default=None)
    r"""Update the full body of an Authorization Server."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    