"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import applicationresponse as shared_applicationresponse
from typing import Optional


@dataclasses.dataclass
class CreateApplicationResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    application_response: Optional[shared_applicationresponse.ApplicationResponse] = dataclasses.field(default=None)
    r"""Create Application"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    