"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import applicationresponse as shared_applicationresponse
from typing import Optional


@dataclasses.dataclass
class GetApplicationRequest:
    
    application_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'applicationId', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class GetApplicationResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    application_response: Optional[shared_applicationresponse.ApplicationResponse] = dataclasses.field(default=None)
    r"""Get Application"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    