"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import accesstokenrequest as shared_accesstokenrequest
from ..shared import accesstokenresponse as shared_accesstokenresponse
from typing import Optional


@dataclasses.dataclass
class IssueTokenRequest:
    
    access_token_request: shared_accesstokenrequest.AccessTokenRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    authorization_server_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'authorizationServerId', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class IssueTokenResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    access_token_response: Optional[shared_accesstokenresponse.AccessTokenResponse] = dataclasses.field(default=None)
    r"""Get an Access Token"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    