"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientsresponse as shared_clientsresponse
from typing import Optional


@dataclasses.dataclass
class ListClientsRequest:
    
    authorization_server_ids: Optional[list[str]] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'authorizationServerIds', 'style': 'form', 'explode': True }})
    

@dataclasses.dataclass
class ListClientsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    clients_response: Optional[shared_clientsresponse.ClientsResponse] = dataclasses.field(default=None)
    r"""Gets a list of clients."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    