"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import templaterequest as shared_templaterequest
from ..shared import templateresponse as shared_templateresponse
from typing import Optional


@dataclasses.dataclass
class UpdateTemplateRequest:
    
    template_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'templateId', 'style': 'simple', 'explode': False }})
    template_request: shared_templaterequest.TemplateRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    

@dataclasses.dataclass
class UpdateTemplateResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    template_response: Optional[shared_templateresponse.TemplateResponse] = dataclasses.field(default=None)
    r"""Update the whole template."""
    