/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateScopeResponse {
    
    public String contentType;
    public CreateScopeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Creates a new client.
     */
    
    public com.cartobucket.auth.api.models.shared.ScopeResponse scopeResponse;
    public CreateScopeResponse withScopeResponse(com.cartobucket.auth.api.models.shared.ScopeResponse scopeResponse) {
        this.scopeResponse = scopeResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public CreateScopeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public CreateScopeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public CreateScopeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
