/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateApplicationSecretRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.cartobucket.auth.api.models.shared.ApplicationSecretRequest applicationSecretRequest;
    public CreateApplicationSecretRequest withApplicationSecretRequest(com.cartobucket.auth.api.models.shared.ApplicationSecretRequest applicationSecretRequest) {
        this.applicationSecretRequest = applicationSecretRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=applicationId")
    public String applicationId;
    public CreateApplicationSecretRequest withApplicationId(String applicationId) {
        this.applicationId = applicationId;
        return this;
    }
    
    public CreateApplicationSecretRequest(@JsonProperty("applicationId") String applicationId) {
        this.applicationId = applicationId;
  }
}
