/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetScopeResponse {
    
    public String contentType;
    public GetScopeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Get the template.
     */
    
    public com.cartobucket.auth.api.models.shared.ScopeResponse scopeResponse;
    public GetScopeResponse withScopeResponse(com.cartobucket.auth.api.models.shared.ScopeResponse scopeResponse) {
        this.scopeResponse = scopeResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public GetScopeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetScopeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetScopeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
