/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetUserInfoResponse {
    
    public String contentType;
    public GetUserInfoResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetUserInfoResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetUserInfoResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Get userinfo
     */
    
    public java.util.Map<String, Object> getUserInfo200ApplicationJSONObject;
    public GetUserInfoResponse withGetUserInfo200ApplicationJSONObject(java.util.Map<String, Object> getUserInfo200ApplicationJSONObject) {
        this.getUserInfo200ApplicationJSONObject = getUserInfo200ApplicationJSONObject;
        return this;
    }
    
    public GetUserInfoResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
