/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class IssueTokenResponse {
    /**
     * Get an Access Token
     */
    
    public com.cartobucket.auth.api.models.shared.AccessTokenResponse accessTokenResponse;
    public IssueTokenResponse withAccessTokenResponse(com.cartobucket.auth.api.models.shared.AccessTokenResponse accessTokenResponse) {
        this.accessTokenResponse = accessTokenResponse;
        return this;
    }
    
    
    public String contentType;
    public IssueTokenResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public IssueTokenResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public IssueTokenResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public IssueTokenResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
