/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListApplicationsResponse {
    /**
     * Get Applications
     */
    
    public com.cartobucket.auth.api.models.shared.ApplicationsResponse applicationsResponse;
    public ListApplicationsResponse withApplicationsResponse(com.cartobucket.auth.api.models.shared.ApplicationsResponse applicationsResponse) {
        this.applicationsResponse = applicationsResponse;
        return this;
    }
    
    
    public String contentType;
    public ListApplicationsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ListApplicationsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListApplicationsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListApplicationsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
