/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.operations;

import com.cartobucket.auth.api.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateAuthorizationServerRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.cartobucket.auth.api.models.shared.AuthorizationServerRequest authorizationServerRequest;
    public UpdateAuthorizationServerRequest withAuthorizationServerRequest(com.cartobucket.auth.api.models.shared.AuthorizationServerRequest authorizationServerRequest) {
        this.authorizationServerRequest = authorizationServerRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=authorizationServerId")
    public String authorizationServerId;
    public UpdateAuthorizationServerRequest withAuthorizationServerId(String authorizationServerId) {
        this.authorizationServerId = authorizationServerId;
        return this;
    }
    
    public UpdateAuthorizationServerRequest(@JsonProperty("AuthorizationServerRequest") com.cartobucket.auth.api.models.shared.AuthorizationServerRequest authorizationServerRequest, @JsonProperty("authorizationServerId") String authorizationServerId) {
        this.authorizationServerRequest = authorizationServerRequest;
        this.authorizationServerId = authorizationServerId;
  }
}
