/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ApplicationRequest {
    @JsonProperty("authorizationServerId")
    public String authorizationServerId;
    public ApplicationRequest withAuthorizationServerId(String authorizationServerId) {
        this.authorizationServerId = authorizationServerId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client_id")
    public String clientId;
    public ApplicationRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("client_secret")
    public String clientSecret;
    public ApplicationRequest withClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
        return this;
    }
    
    @JsonProperty("name")
    public String name;
    public ApplicationRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("profile")
    public java.util.Map<String, Object> profile;
    public ApplicationRequest withProfile(java.util.Map<String, Object> profile) {
        this.profile = profile;
        return this;
    }
    
    public ApplicationRequest(@JsonProperty("authorizationServerId") String authorizationServerId, @JsonProperty("name") String name) {
        this.authorizationServerId = authorizationServerId;
        this.name = name;
  }
}
