/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WellKnown - Returns a well-known configuration object.
 */
public class WellKnown {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authorization_endpoint")
    public String authorizationEndpoint;
    public WellKnown withAuthorizationEndpoint(String authorizationEndpoint) {
        this.authorizationEndpoint = authorizationEndpoint;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("claims_supported")
    public WellKnownClaimsSupportedEnum[] claimsSupported;
    public WellKnown withClaimsSupported(WellKnownClaimsSupportedEnum[] claimsSupported) {
        this.claimsSupported = claimsSupported;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code_challenge_methods_supported")
    public WellKnownCodeChallengeMethodsSupportedEnum[] codeChallengeMethodsSupported;
    public WellKnown withCodeChallengeMethodsSupported(WellKnownCodeChallengeMethodsSupportedEnum[] codeChallengeMethodsSupported) {
        this.codeChallengeMethodsSupported = codeChallengeMethodsSupported;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("grant_types_supported")
    public String[] grantTypesSupported;
    public WellKnown withGrantTypesSupported(String[] grantTypesSupported) {
        this.grantTypesSupported = grantTypesSupported;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id_token_signing_alg_values_supported")
    public WellKnownIdTokenSigningAlgValuesSupportedEnum[] idTokenSigningAlgValuesSupported;
    public WellKnown withIdTokenSigningAlgValuesSupported(WellKnownIdTokenSigningAlgValuesSupportedEnum[] idTokenSigningAlgValuesSupported) {
        this.idTokenSigningAlgValuesSupported = idTokenSigningAlgValuesSupported;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("issuer")
    public String issuer;
    public WellKnown withIssuer(String issuer) {
        this.issuer = issuer;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("jwks_uri")
    public String jwksUri;
    public WellKnown withJwksUri(String jwksUri) {
        this.jwksUri = jwksUri;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_types_supported")
    public WellKnownResponseTypesSupportedEnum[] responseTypesSupported;
    public WellKnown withResponseTypesSupported(WellKnownResponseTypesSupportedEnum[] responseTypesSupported) {
        this.responseTypesSupported = responseTypesSupported;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("revocation_endpoint")
    public String revocationEndpoint;
    public WellKnown withRevocationEndpoint(String revocationEndpoint) {
        this.revocationEndpoint = revocationEndpoint;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scopes_supported")
    public WellKnownScopesSupportedEnum[] scopesSupported;
    public WellKnown withScopesSupported(WellKnownScopesSupportedEnum[] scopesSupported) {
        this.scopesSupported = scopesSupported;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subject_types_supported")
    public WellKnownSubjectTypesSupportedEnum[] subjectTypesSupported;
    public WellKnown withSubjectTypesSupported(WellKnownSubjectTypesSupportedEnum[] subjectTypesSupported) {
        this.subjectTypesSupported = subjectTypesSupported;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("token_endpoint")
    public String tokenEndpoint;
    public WellKnown withTokenEndpoint(String tokenEndpoint) {
        this.tokenEndpoint = tokenEndpoint;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("token_endpoint_auth_methods_supported")
    public WellKnownTokenEndpointAuthMethodsSupportedEnum[] tokenEndpointAuthMethodsSupported;
    public WellKnown withTokenEndpointAuthMethodsSupported(WellKnownTokenEndpointAuthMethodsSupportedEnum[] tokenEndpointAuthMethodsSupported) {
        this.tokenEndpointAuthMethodsSupported = tokenEndpointAuthMethodsSupported;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userinfo_endpoint")
    public String userinfoEndpoint;
    public WellKnown withUserinfoEndpoint(String userinfoEndpoint) {
        this.userinfoEndpoint = userinfoEndpoint;
        return this;
    }
    
    public WellKnown(){}
}
