/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WellKnownClaimsSupportedEnum {
    AUD("aud"),
    EXP("exp"),
    FAMILY_NAME("family_name"),
    GIVEN_NAME("given_name"),
    IAT("iat"),
    ISS("iss"),
    NAME("name"),
    SUB("sub");

    @JsonValue
    public final String value;

    private WellKnownClaimsSupportedEnum(String value) {
        this.value = value;
    }
}
