"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from sdk.models import operations, shared
from typing import Optional

class Templates:
    r"""Templates are used to render information such as the login page."""
    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str
    _language: str
    _sdk_version: str
    _gen_version: str

    def __init__(self, client: requests_http.Session, security_client: requests_http.Session, server_url: str, language: str, sdk_version: str, gen_version: str) -> None:
        self._client = client
        self._security_client = security_client
        self._server_url = server_url
        self._language = language
        self._sdk_version = sdk_version
        self._gen_version = gen_version
        
    def create_template(self, request: shared.TemplateRequest) -> operations.CreateTemplateResponse:
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/templates/'
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "request", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = self._client
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.CreateTemplateResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.TemplateResponse])
                res.template_response = out

        return res

    def delete_template(self, request: operations.DeleteTemplateRequest) -> operations.DeleteTemplateResponse:
        base_url = self._server_url
        
        url = utils.generate_url(operations.DeleteTemplateRequest, base_url, '/templates/{templateId}/', request)
        
        
        client = self._client
        
        http_res = client.request('DELETE', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.DeleteTemplateResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        

        return res

    def get_template(self, request: operations.GetTemplateRequest) -> operations.GetTemplateResponse:
        base_url = self._server_url
        
        url = utils.generate_url(operations.GetTemplateRequest, base_url, '/templates/{templateId}/', request)
        
        
        client = self._client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.GetTemplateResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.TemplateResponse])
                res.template_response = out

        return res

    def list_templates(self, request: operations.ListTemplatesRequest) -> operations.ListTemplatesResponse:
        base_url = self._server_url
        
        url = base_url.removesuffix('/') + '/templates/'
        
        query_params = utils.get_query_params(operations.ListTemplatesRequest, request)
        
        client = self._client
        
        http_res = client.request('GET', url, params=query_params)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ListTemplatesResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.TemplateResponse])
                res.template_response = out

        return res

    def update_template(self, request: operations.UpdateTemplateRequest) -> operations.UpdateTemplateResponse:
        base_url = self._server_url
        
        url = utils.generate_url(operations.UpdateTemplateRequest, base_url, '/templates/{templateId}/', request)
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "template_request", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = self._client
        
        http_res = client.request('PUT', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.UpdateTemplateResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.TemplateResponse])
                res.template_response = out

        return res

    