/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ApplicationSecretsResponse - List the secrets
 */
public class ApplicationSecretsResponse {
    @JsonProperty("applicationSecrets")
    public ApplicationSecretResponse[] applicationSecrets;
    public ApplicationSecretsResponse withApplicationSecrets(ApplicationSecretResponse[] applicationSecrets) {
        this.applicationSecrets = applicationSecrets;
        return this;
    }
    
    public ApplicationSecretsResponse(@JsonProperty("applicationSecrets") ApplicationSecretResponse[] applicationSecrets) {
        this.applicationSecrets = applicationSecrets;
  }
}
