/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AuthorizationServerResponse - Create a new Authorization Server.
 */
public class AuthorizationServerResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("audience")
    public String audience;
    public AuthorizationServerResponse withAudience(String audience) {
        this.audience = audience;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authorizationCodeTokenExpiration")
    public Integer authorizationCodeTokenExpiration;
    public AuthorizationServerResponse withAuthorizationCodeTokenExpiration(Integer authorizationCodeTokenExpiration) {
        this.authorizationCodeTokenExpiration = authorizationCodeTokenExpiration;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("clientCredentialsTokenExpiration")
    public Integer clientCredentialsTokenExpiration;
    public AuthorizationServerResponse withClientCredentialsTokenExpiration(Integer clientCredentialsTokenExpiration) {
        this.clientCredentialsTokenExpiration = clientCredentialsTokenExpiration;
        return this;
    }
    
    @JsonProperty("createdOn")
    public String createdOn;
    public AuthorizationServerResponse withCreatedOn(String createdOn) {
        this.createdOn = createdOn;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;
    public AuthorizationServerResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("name")
    public String name;
    public AuthorizationServerResponse withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("serverUrl")
    public String serverUrl;
    public AuthorizationServerResponse withServerUrl(String serverUrl) {
        this.serverUrl = serverUrl;
        return this;
    }
    
    @JsonProperty("updatedOn")
    public String updatedOn;
    public AuthorizationServerResponse withUpdatedOn(String updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }
    
    public AuthorizationServerResponse(@JsonProperty("createdOn") String createdOn, @JsonProperty("name") String name, @JsonProperty("updatedOn") String updatedOn) {
        this.createdOn = createdOn;
        this.name = name;
        this.updatedOn = updatedOn;
  }
}
