/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Jwk {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("alg")
    public String alg;
    public Jwk withAlg(String alg) {
        this.alg = alg;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("e")
    public String e;
    public Jwk withE(String e) {
        this.e = e;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kid")
    public String kid;
    public Jwk withKid(String kid) {
        this.kid = kid;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("kty")
    public String kty;
    public Jwk withKty(String kty) {
        this.kty = kty;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("n")
    public String n;
    public Jwk withN(String n) {
        this.n = n;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("use")
    public String use;
    public Jwk withUse(String use) {
        this.use = use;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("x5c")
    public String[] x5c;
    public Jwk withX5c(String[] x5c) {
        this.x5c = x5c;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("x5t")
    public String x5t;
    public Jwk withX5t(String x5t) {
        this.x5t = x5t;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("x5t#S256")
    public String x5tNumberS256;
    public Jwk withX5tNumberS256(String x5tNumberS256) {
        this.x5tNumberS256 = x5tNumberS256;
        return this;
    }
    
    public Jwk(){}
}
