/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ScopeRequest {
    @JsonProperty("authorizationServerId")
    public String authorizationServerId;
    public ScopeRequest withAuthorizationServerId(String authorizationServerId) {
        this.authorizationServerId = authorizationServerId;
        return this;
    }
    
    @JsonProperty("name")
    public String name;
    public ScopeRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    public ScopeRequest(@JsonProperty("authorizationServerId") String authorizationServerId, @JsonProperty("name") String name) {
        this.authorizationServerId = authorizationServerId;
        this.name = name;
  }
}
