/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WellKnownSubjectTypesSupportedEnum {
    PUBLIC_("public");

    @JsonValue
    public final String value;

    private WellKnownSubjectTypesSupportedEnum(String value) {
        this.value = value;
    }
}
