/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.cartobucket.auth.api.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WellKnownScopesSupportedEnum {
    OPENID("openid"),
    EMAIL("email"),
    PROFILE("profile");

    @JsonValue
    public final String value;

    private WellKnownScopesSupportedEnum(String value) {
        this.value = value;
    }
}
